# Generated by Django 4.1 on 2023-07-18 15:43

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ("standard_encoding", "0001_initial"),
        (
            "menu_management",
            "0005_alter_provenancesystemsettingsmenumanagementmenuroledisplay_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="provenancesystemsettingsmenumanagementmenuparameter",
            name="NODE_TYPE",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                verbose_name="菜单节点类型",
            ),
        ),
    ]
