# Generated by Django 4.1 on 2023-07-20 17:48

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "menu_management",
            "0006_provenancesystemsettingsmenumanagementmenuparameter_node_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="provenancesystemsettingsmenumanagementmenuparameter",
            name="ID_MENU",
            field=simplepro.components.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_management.provenancesystemsettingsmenumanagementmenu",
                unique=True,
                verbose_name="菜单",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="provenancesystemsettingsmenumanagementmenuparameter",
            unique_together={("APP_URL_NAME", "URL_NAME")},
        ),
    ]
