# Generated by Django 4.1 on 2023-07-21 12:49

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ("routing_management", "0001_initial"),
        (
            "menu_management",
            "0008_alter_provenancesystemsettingsmenumanagementmenuparameter_id_menu",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="provenancesystemsettingsmenumanagementmenuparameter",
            name="NAME_SPACE",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="routing_management.provenancesystemsettingsroutingmanagementnamespacename",
                verbose_name="路由",
            ),
        ),
    ]
