# Generated by Django 4.1 on 2023-07-28 17:55

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("standard_encoding", "0001_initial"),
        (
            "personal_Information",
            "0003_alter_transactionsocialcultureethnicpopulationpersonalinformationperson_date_of_death_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDataRecordsSystem",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ID_UNIQUE",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="唯一标识"
                    ),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="系统名称"
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="记录人员",
                    ),
                ),
                (
                    "SYSTEM_CATEGORY",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="所属系统",
                    ),
                ),
            ],
            options={
                "verbose_name": "账户系统表",
                "verbose_name_plural": "账户系统表",
                "db_table": "ProvenanceSystemFunctionDataRecordsSystem",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDataRecordsTag",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, unique=True, verbose_name="标签名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "文件对象",
                "verbose_name_plural": "文件对象",
                "db_table": "ProvenanceSystemFunctionDataRecordsTag",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDataRecordsSystemFolder",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "INODE",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="工作目录标识"
                    ),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="工作目录名称"
                    ),
                ),
                (
                    "PATH",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="工作目录路径"
                    ),
                ),
                (
                    "ID_SYSTEM",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_records.provenancesystemfunctiondatarecordssystem",
                        verbose_name="账户系统",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作目录",
                "verbose_name_plural": "工作目录",
                "db_table": "ProvenanceSystemFunctionDataRecordsSystemFolder",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDataRecordsSystemFileObject",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "INODE",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="工作目录标识"
                    ),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="工作目录名称"
                    ),
                ),
                (
                    "PATH",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="工作目录路径"
                    ),
                ),
                (
                    "ID_FOLDER",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_records.provenancesystemfunctiondatarecordssystemfolder",
                        verbose_name="工作目录",
                    ),
                ),
                (
                    "TYPE",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="对象类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件对象",
                "verbose_name_plural": "文件对象",
                "db_table": "ProvenanceSystemFunctionDataRecordsSystemFileObject",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDataRecordsFileObjectTag",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ID_FILE_OBJECT",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_records.provenancesystemfunctiondatarecordssystemfileobject",
                        verbose_name="标签",
                    ),
                ),
                (
                    "ID_TAG",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_records.provenancesystemfunctiondatarecordstag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件对象标签",
                "verbose_name_plural": "文件对象标签",
                "db_table": "ProvenanceSystemFunctionDataRecordsFileObjectTag",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
