# Generated by Django 4.1 on 2023-07-30 17:24

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "personal_Information",
            "0004_alter_transactionsocialcultureethnicpopulationpersonalinformationperson_date_of_death_and_more",
        ),
        ("standard_encoding", "0001_initial"),
        ("data_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provenancesystemfunctiondatarecordstag",
            name="ID_FOLDER",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_records.provenancesystemfunctiondatarecordssystemfolder",
                verbose_name="工作目录",
            ),
        ),
        migrations.AlterField(
            model_name="provenancesystemfunctiondatarecordstag",
            name="NAME",
            field=simplepro.components.fields.CharField(
                max_length=255, verbose_name="标签名称"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="provenancesystemfunctiondatarecordsfileobjecttag",
            unique_together={("ID_TAG", "ID_FILE_OBJECT")},
        ),
        migrations.AlterUniqueTogether(
            name="provenancesystemfunctiondatarecordssystem",
            unique_together={("ID_PERSON", "ID_UNIQUE", "SYSTEM_CATEGORY", "NAME")},
        ),
        migrations.AlterUniqueTogether(
            name="provenancesystemfunctiondatarecordssystemfileobject",
            unique_together={("ID_FOLDER", "INODE")},
        ),
        migrations.AlterUniqueTogether(
            name="provenancesystemfunctiondatarecordssystemfolder",
            unique_together={("ID_SYSTEM", "INODE")},
        ),
        migrations.AlterUniqueTogether(
            name="provenancesystemfunctiondatarecordstag",
            unique_together={("ID_FOLDER", "NAME")},
        ),
    ]
