# Generated by Django 4.1 on 2023-07-30 19:26

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_management",
            "0009_provenancesystemsettingsaccountmanagementpermissionmenudisplay_id_display_and_more",
        ),
        ("standard_encoding", "0001_initial"),
        (
            "data_records",
            "0002_provenancesystemfunctiondatarecordstag_id_folder_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="provenancesystemfunctiondatarecordssystem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="provenancesystemfunctiondatarecordssystem",
            name="ID_SUBSCRIBER",
            field=simplepro.components.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account_management.provenancesystemsettingsaccountmanagementsubscriber",
                verbose_name="订阅用户",
            ),
        ),
        migrations.AlterField(
            model_name="provenancesystemfunctiondatarecordsfileobjecttag",
            name="ID_FILE_OBJECT",
            field=simplepro.components.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="data_records.provenancesystemfunctiondatarecordssystemfileobject",
                verbose_name="文件对象",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="provenancesystemfunctiondatarecordssystem",
            unique_together={("ID_SUBSCRIBER", "ID_UNIQUE", "SYSTEM_CATEGORY", "NAME")},
        ),
        migrations.RemoveField(
            model_name="provenancesystemfunctiondatarecordssystem",
            name="ID_PERSON",
        ),
    ]
