# Generated by Django 4.1 on 2023-07-30 19:27

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_management",
            "0009_provenancesystemsettingsaccountmanagementpermissionmenudisplay_id_display_and_more",
        ),
        (
            "data_records",
            "0003_alter_provenancesystemfunctiondatarecordssystem_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="provenancesystemfunctiondatarecordssystem",
            name="ID_SUBSCRIBER",
            field=simplepro.components.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account_management.provenancesystemsettingsaccountmanagementsubscriber",
                verbose_name="订阅用户",
            ),
        ),
    ]
