# Generated by Django 4.1 on 2023-07-31 11:55

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("standard_encoding", "0001_initial"),
        ("data_records", "0005_provenancesystemfunctiondatarecordstagtitle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDataRecordsSystemFileObjectInherit",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "INHERIT_VALUE",
                    models.BooleanField(default=True, verbose_name="继承值"),
                ),
                (
                    "ID_FILE_OBJECT",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_records.provenancesystemfunctiondatarecordssystemfileobject",
                        verbose_name="文件对象",
                    ),
                ),
                (
                    "INHERIT_TYPE",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="继承类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件对象继承配置",
                "verbose_name_plural": "文件对象继承配置",
                "db_table": "ProvenanceSystemFunctionDataRecordsSystemFileObjectInherit",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
