# Generated by Django 4.1 on 2023-07-20 16:20

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("standard_encoding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningTheHumanitiesHumanitiesArtsLiteratureArtContent",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "CONTENT",
                    simplepro.editor.fields.MDTextField(
                        default=None, unique=True, verbose_name="文字内容"
                    ),
                ),
            ],
            options={
                "verbose_name": "文字艺术",
                "verbose_name_plural": "文字艺术",
                "db_table": "LearningTheHumanitiesHumanitiesArtsLiteratureArtContent",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="LearningTheHumanitiesHumanitiesArtsLiteratureArtContentType",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "LITERATURE_ART_CODE",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="文字艺术类别",
                    ),
                ),
                (
                    "LITERATURE_ART_ID",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="literature_art.learningthehumanitieshumanitiesartsliteratureartcontent",
                        verbose_name="文字内容",
                    ),
                ),
            ],
            options={
                "verbose_name": "文字艺术类别",
                "verbose_name_plural": "文字艺术类别",
                "db_table": "LearningTheHumanitiesHumanitiesArtsLiteratureArtContentType",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
