# Generated by Django 4.1 on 2023-07-21 09:42

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProvenanceSystemSettingsRoutingManagementNameSpace",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NAME_SPACE",
                    simplepro.components.fields.CharField(
                        max_length=255, unique=True, verbose_name="应用路由"
                    ),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="中文描述"
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, null=True, verbose_name="详情"
                    ),
                ),
            ],
            options={
                "verbose_name": "应用路由",
                "verbose_name_plural": "应用路由",
                "db_table": "ProvenanceSystemSettingsRoutingManagementNameSpace",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemSettingsRoutingManagementNameSpaceName",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NAME_SPACE_NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="应用路由"
                    ),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="中文描述"
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, null=True, verbose_name="详情"
                    ),
                ),
                (
                    "ID_NAME_SPACE",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routing_management.provenancesystemsettingsroutingmanagementnamespace",
                        verbose_name="应用路由",
                    ),
                ),
            ],
            options={
                "verbose_name": "应用子路由",
                "verbose_name_plural": "应用子路由",
                "db_table": "ProvenanceSystemSettingsRoutingManagementNameSpaceName",
                "ordering": ["-CREATE_TIME"],
                "unique_together": {("ID_NAME_SPACE", "NAME_SPACE_NAME")},
            },
        ),
    ]
