# Generated by Django 4.1 on 2023-07-12 16:03

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0003_alter_transactioneconomyindustryproductsprojectbasis_project_creation_time_and_more",
        ),
        ("standard_encoding", "0001_initial"),
        ("products", "0002_transactioneconomyindustryproductsproductsserver_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionEconomyIndustryProductsProductsProject",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, null=True, verbose_name="详情描述"
                    ),
                ),
                (
                    "CORRELATION_CODE",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="关联",
                    ),
                ),
                (
                    "ID_PRODUCTS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.transactioneconomyindustryproductsbasis",
                        verbose_name="产品",
                    ),
                ),
                (
                    "ID_PROJECT",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.transactioneconomyindustryproductsprojectbasis",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目对应产品",
                "verbose_name_plural": "项目对应产品",
                "db_table": "TransactionEconomyIndustryProductsProductsProject",
                "ordering": ["-CREATE_TIME"],
                "unique_together": {("ID_PROJECT", "ID_PRODUCTS", "CORRELATION_CODE")},
            },
        ),
    ]
