# Generated by Django 4.1 on 2023-08-23 22:46

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_transactioneconomyindustryproductsproductsproject"),
        (
            "organizations",
            "0006_alter_transactioneconomyindustryorganizationsbases_country_create_time_and_more",
        ),
        ("standard_encoding", "0001_initial"),
        (
            "personal_Information",
            "0002_alter_transactionsocialcultureethnicpopulationpersonalinformationperson_date_of_death_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDevelopInformationSystem",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CRITERION",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="编码"
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, null=True, verbose_name="详情描述"
                    ),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="系统名称"
                    ),
                ),
                (
                    "IP",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=16, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "IS_VIRTUAL_MACHINE",
                    models.BooleanField(default=False, verbose_name="是否虚拟机"),
                ),
                (
                    "ARCHITECTURE",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="系统信息_系统架构",
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="系统架构",
                    ),
                ),
                (
                    "ID_ORGANIZATIONS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.transactioneconomyindustryorganizationsbases",
                        verbose_name="组织",
                    ),
                ),
                (
                    "ID_PERSON",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_Information.transactionsocialcultureethnicpopulationpersonalinformationperson",
                        verbose_name="人员",
                    ),
                ),
                (
                    "ID_PRODUCTS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.transactioneconomyindustryproductsbasis",
                        verbose_name="依托产品",
                    ),
                ),
                (
                    "ID_SYSTEM",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="develop_information.provenancesystemfunctiondevelopinformationsystem",
                        verbose_name="所属主机",
                    ),
                ),
                (
                    "SYSTEM_CATEGORY",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="系统信息_所属系统",
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="所属系统",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统信息",
                "verbose_name_plural": "系统信息",
                "db_table": "ProvenanceSystemFunctionDevelopInformationSystem",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDevelopInformationSystemService",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CRITERION",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="编码"
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, null=True, verbose_name="详情描述"
                    ),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="服务名称"
                    ),
                ),
                (
                    "ID_ORGANIZATIONS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.transactioneconomyindustryorganizationsbases",
                        verbose_name="所属组织",
                    ),
                ),
                (
                    "ID_PRODUCTS",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.transactioneconomyindustryproductsbasis",
                        verbose_name="依托产品",
                    ),
                ),
                (
                    "ID_SYSTEM",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="develop_information.provenancesystemfunctiondevelopinformationsystem",
                        verbose_name="所属主机",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统服务信息",
                "verbose_name_plural": "系统服务信息",
                "db_table": "ProvenanceSystemFunctionDevelopInformationSystemService",
                "ordering": ["-CREATE_TIME"],
            },
        ),
        migrations.CreateModel(
            name="ProvenanceSystemFunctionDevelopInformationSystemServiceProt",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CRITERION",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="编码"
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, null=True, verbose_name="详情描述"
                    ),
                ),
                (
                    "PROT",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="端口"
                    ),
                ),
                (
                    "ID_SYSTEM_SERVICE",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="develop_information.provenancesystemfunctiondevelopinformationsystemservice",
                        verbose_name="系统服务",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统服务端口信息",
                "verbose_name_plural": "系统服务端口信息",
                "db_table": "ProvenanceSystemFunctionDevelopInformationSystemServiceProt",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
