# Generated by Django 4.1 on 2023-07-11 13:35

from django.db import migrations, models
import simplepro.components.fields
import simplepro.editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionEconomyIndustryProductsProjectBasis",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "PROJECT_NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="项目名称"
                    ),
                ),
                (
                    "PROJECT_CREATION_TIME",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-07-11 13:35:11",
                        null=True,
                        verbose_name="项目开始时间",
                    ),
                ),
                (
                    "PROJECT_END_TIME",
                    simplepro.components.fields.DateField(
                        blank=True,
                        default="2023-07-11 13:35:11",
                        null=True,
                        verbose_name="项目结束时间",
                    ),
                ),
                (
                    "DETAIL",
                    simplepro.editor.fields.MDTextField(
                        blank=True, null=True, verbose_name="详情描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "项目基本信息",
                "verbose_name_plural": "项目基本信息",
                "db_table": "TransactionEconomyIndustryProductsProjectBasis",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
