# Generated by Django 4.1 on 2023-07-12 16:03

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0002_alter_transactioneconomyindustryproductsprojectbasis_project_creation_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioneconomyindustryproductsprojectbasis",
            name="PROJECT_CREATION_TIME",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-07-12 16:03:03",
                null=True,
                verbose_name="项目开始时间",
            ),
        ),
        migrations.AlterField(
            model_name="transactioneconomyindustryproductsprojectbasis",
            name="PROJECT_END_TIME",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-07-12 16:03:03",
                null=True,
                verbose_name="项目结束时间",
            ),
        ),
        migrations.AlterField(
            model_name="transactioneconomyindustryproductsprojectorganization",
            name="PROPORTION",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="占比%",
            ),
        ),
    ]
