# Generated by Django 4.1 on 2023-07-11 21:46

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("standard_encoding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionEconomyIndustryProductsProjectServer",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="服务器名称"
                    ),
                ),
                (
                    "INSTANCE_ID",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="实例ID"
                    ),
                ),
                (
                    "PUBLIC_NETWORK",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=16, null=True, verbose_name="公网IP"
                    ),
                ),
                (
                    "REGION",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=255, null=True, verbose_name="地域"
                    ),
                ),
                (
                    "INSIDE_OUTSIDE_CODE",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="互联网类别",
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="互联网类别",
                    ),
                ),
                (
                    "MIRROR_CATEGORY",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="镜像名称",
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="镜像名称",
                    ),
                ),
                (
                    "SYSTEM_CATEGORY",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="所属系统",
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="所属系统",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务器信息",
                "verbose_name_plural": "服务器信息",
                "db_table": "TransactionEconomyIndustryProductsProjectServer",
                "ordering": ["-CREATE_TIME"],
            },
        ),
    ]
