# Generated by Django 4.1 on 2023-07-22 19:57

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("standard_encoding", "0001_initial"),
        ("country", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiongeographypoliticscountrycollect",
            name="NAME",
            field=simplepro.components.fields.CharField(
                blank=True, max_length=255, null=True, verbose_name="国家名称"
            ),
        ),
        migrations.CreateModel(
            name="TransactionGeographyPoliticsCountryCollectCall",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="名称"
                    ),
                ),
                (
                    "ID_NATION",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.transactiongeographypoliticscountrycollect",
                        verbose_name="国家",
                    ),
                ),
                (
                    "NAME_CODE",
                    simplepro.components.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="称呼类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "国家称呼信息",
                "verbose_name_plural": "国家称呼信息",
                "db_table": "TransactionGeographyPoliticsCountryCollectCall",
                "ordering": ["-CREATE_TIME"],
                "unique_together": {("ID_NATION", "NAME_CODE", "NAME")},
            },
        ),
    ]
