# Generated by Django 4.1 on 2023-08-23 22:46

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0005_alter_transactioneconomyindustryorganizationscertificate_date_end_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioneconomyindustryorganizationsbases",
            name="COUNTRY_CREATE_TIME",
            field=simplepro.components.fields.DateField(
                blank=True, default="2023-08-23", null=True, verbose_name="成立时间"
            ),
        ),
        migrations.AlterField(
            model_name="transactioneconomyindustryorganizationsbases",
            name="COUNTRY_END_TIME",
            field=simplepro.components.fields.DateField(
                blank=True, default="2023-08-23", null=True, verbose_name="结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="transactioneconomyindustryorganizationscertificate",
            name="DATE_END",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-08-23 22:46:11",
                null=True,
                verbose_name="组织证件号有效结束日期",
            ),
        ),
        migrations.AlterField(
            model_name="transactioneconomyindustryorganizationscertificate",
            name="DATE_ISSUED",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-08-23 22:46:11",
                null=True,
                verbose_name="签发日期",
            ),
        ),
        migrations.AlterField(
            model_name="transactioneconomyindustryorganizationscertificate",
            name="DATE_START",
            field=simplepro.components.fields.DateField(
                blank=True,
                default="2023-08-23 22:46:11",
                null=True,
                verbose_name="组织证件号有效开始日期",
            ),
        ),
    ]
