# Generated by Django 4.1 on 2023-07-27 09:03

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("standard_encoding", "0001_initial"),
        ("biology", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningnaturalsciencebiologicalspecies",
            name="NAME_ENGLISH",
        ),
        migrations.RemoveField(
            model_name="learningnaturalsciencebiologicalspecies",
            name="NAME_REFERRED_TO_AS",
        ),
        migrations.AddField(
            model_name="learningnaturalsciencebiologicalspecies",
            name="MAN_MODE",
            field=models.BooleanField(default=False, verbose_name="人工培育"),
        ),
        migrations.AlterField(
            model_name="learningnaturalsciencebiologicalspecies",
            name="NAME_CHINESE",
            field=simplepro.components.fields.CharField(
                max_length=255, verbose_name="中文描述"
            ),
        ),
        migrations.CreateModel(
            name="LearningNaturalScienceBiologicalSpeciesCall",
            fields=[
                (
                    "ID",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="标识",
                    ),
                ),
                (
                    "CREATE_TIME",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "UPDATE_TIME",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "STATUS_IS_DELETE",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
                (
                    "STATUS_IS_EFFECTIVE",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "ENTERPRISE_NAME",
                    simplepro.components.fields.CharField(
                        max_length=255, verbose_name="名称"
                    ),
                ),
                (
                    "ENTERPRISE_NAME_CODE",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="standard_encoding.provenancesystemsettingsstandardcodemaindict",
                        verbose_name="生物种类类别",
                    ),
                ),
                (
                    "ID_BIOLOGICAL_SPECIE",
                    simplepro.components.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biology.learningnaturalsciencebiologicalspecies",
                        verbose_name="生物种类",
                    ),
                ),
            ],
            options={
                "verbose_name": "生物种类称呼",
                "verbose_name_plural": "生物种类称呼",
                "db_table": "LearningNaturalScienceBiologicalSpeciesCall",
                "ordering": ["-CREATE_TIME"],
                "unique_together": {
                    ("ID_BIOLOGICAL_SPECIE", "ENTERPRISE_NAME_CODE", "ENTERPRISE_NAME")
                },
            },
        ),
    ]
